version: "3"
services:
 springboot:
   image: veda1998/spring-boot:TAG 
   ports:
   - 8080:8080
   working_dir: /opt/app 
   environment:
   - MONGO_DB_HOSTNAME=mongo
   - MONGO_DB_USERNAME=robinuttappa
   - MONGO_DB_PASSWORD=8975758051
   networks:
    - springappnetwork
   depends_on:
     - mongo 
   deploy:
     replicas: 2
     update_config:
      parallelism: 1
      delay: 25s
     restart_policy:
      condition: on-failure
      delay: 11s
      max_attempts: 5

 mongo:
   image: mongo:latest
   environment:
   - MONGO_INITDB_ROOT_USERNAME=robinuttappa
   - MONGO_INITDB_ROOT_PASSWORD=8975758051
   networks:
    - springappnetwork
   volumes: 
   - mongovol:/data/db
   restart: always 
networks:
 springappnetwork:
volumes:
 mongovol:  
